default: &default
  adapter: postgresql

development:
  <<: *default
  # database: cardology_production_copy
  database: cardology_development
  username: postgres
  password: password

test:
  <<: *default
  database: cardology_test
