default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  port: 5434

development:
  <<: *default
  # database: cardology_production_copy
  database: cardology_development

test:
  <<: *default
  database: cardology_test
